import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import Navbar from './components/navbar/navbar'
import Footer from './components/navbar/footer'
import { Toaster } from 'react-hot-toast'
import MainNav from './components/navbar/mainNav'
import Popular from './components/news/popular'
const inter = Inter({ subsets: ['latin'] })
import NextTopLoader from 'nextjs-toploader';
import Login from './components/auth/login'
import Profile from './components/auth/profile'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default  function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader height={2} color='#00a460'   showSpinner={false} />
        <Toaster />
        <MainNav />
        <div className=' md:flex mt-20 mb-10 '>
        <div className='w-full overflow-scroll'>
        {children}
        </div>
          <Popular />
        </div>
        <Footer />
        </body>
    </html>
  )
}
